name: WIF

on:
  workflow_dispatch:

jobs:
  main:
    name: CI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
      
      - name: Install go
        uses: actions/setup-go@v7.0.0
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Build
        run: make build

      - name: Get access token
        run: |
          TOKEN=$(./bin/stackit auth activate-service-account --use-oidc --only-print-access-token --verbosity debug)
          echo "::add-mask::$TOKEN"
          echo "STACKIT_ACCESS_TOKEN=$TOKEN" >> "$GITHUB_ENV"
          echo "token=$TOKEN" >> "$GITHUB_OUTPUT"
        env:
          STACKIT_SERVICE_ACCOUNT_EMAIL: marcelj-2g78bs1@sa.stackit.cloud

      - name: Execute command
        run: ./bin/stackit network list --project-id "$PROJECT_ID"
        env:
          PROJECT_ID: 66b03760-125b-4c63-9624-741e8a418c02